version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092

  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  chronograf:
    image: chronograf
    volumes:
      - chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    command: --influxdb-url=http://influxdb:8086

volumes:
  influxdb:
  grafana:
  chronograf: